"""Generate the bundled PostgreSQL seed script from the canonical GAAP demo.

Run this module from the repo root to refresh
``src/context_manager/demo/assets/seed-postgres.sql`` whenever the demo
schema or data changes::

    cd packages/datapaw-context
    python -m context_manager.demo.generate

The generated SQL is idempotent (it drops and recreates the table) and
contains exactly the 475 rows expected by the demo verification.
"""

from __future__ import annotations

import argparse
import random
import sys
from datetime import date, timedelta
from pathlib import Path


_ASSETS_DIR = Path(__file__).with_name("assets")
DEFAULT_OUTPUT = _ASSETS_DIR / "seed-postgres.sql"

DEMO_SCHEMA = """DROP TABLE IF EXISTS gaap_metrics;
DROP TABLE IF EXISTS dws_gaap_di;

CREATE TABLE dws_gaap_di (
    ds DATE NOT NULL,
    product TEXT NOT NULL,
    region TEXT NOT NULL,
    user_type TEXT NOT NULL,
    user_id TEXT PRIMARY KEY,
    gaap_val NUMERIC(18, 2) NOT NULL,
    ytd_gaap NUMERIC(18, 2) NOT NULL
);

CREATE INDEX idx_dws_gaap_di_product_date ON dws_gaap_di (product, ds);
CREATE INDEX idx_dws_gaap_di_valid_user ON dws_gaap_di (product, ytd_gaap);
"""

EXPECTED_ROW_COUNT = 475


def demo_rows() -> list[tuple[str, str, str, str, str, float, float]]:
    """Return the fictional GAAP rows shipped with the public demo bundle."""
    rng = random.Random(42)
    rows: list[tuple[str, str, str, str, str, float, float]] = []
    start = date(2026, 3, 1)
    products = ["X", "Y"]
    regions = ["North", "South", "East", "West"]
    user_types = ["student", "enterprise", "individual"]
    user_seq = 0

    for day_offset in range(15):
        ds = start + timedelta(days=day_offset)
        ds_value = ds.isoformat()
        for _ in range(30):
            user_seq += 1
            rows.append(
                (
                    ds_value,
                    rng.choice(products),
                    rng.choice(regions),
                    rng.choice(user_types),
                    f"u{user_seq:05d}",
                    round(rng.uniform(1.0, 8.0), 2),
                    round(rng.uniform(0.0, 25.0), 2),
                ),
            )

        if ds == date(2026, 3, 10):
            for _ in range(15):
                user_seq += 1
                rows.append(
                    (
                        ds_value,
                        "X",
                        rng.choice(regions),
                        "student",
                        f"u{user_seq:05d}",
                        round(rng.uniform(40.0, 60.0), 2),
                        round(rng.uniform(15.0, 30.0), 2),
                    ),
                )
            for _ in range(10):
                user_seq += 1
                rows.append(
                    (
                        ds_value,
                        "X",
                        "North",
                        "enterprise",
                        f"u{user_seq:05d}",
                        round(rng.uniform(70.0, 100.0), 2),
                        round(rng.uniform(20.0, 40.0), 2),
                    ),
                )
    return rows


def _escape(value: object) -> str:
    if isinstance(value, str):
        return "'" + value.replace("'", "''") + "'"
    return str(value)


def generate_seed_sql() -> str:
    """Return the complete PostgreSQL seed script as a string."""
    lines = [
        "-- DataPaw GAAP demo seed",
        "-- Generated by context_manager.demo.generate",
        "-- Do not edit manually; regenerate instead.",
        "",
        DEMO_SCHEMA.strip(),
        "",
        "INSERT INTO dws_gaap_di (ds, product, region, user_type, user_id, gaap_val, ytd_gaap) VALUES",
    ]
    rows = demo_rows()
    formatted = [
        f"    ({', '.join(_escape(v) for v in row)})" for row in rows
    ]
    lines[-1] = lines[-1] + "\n" + ",\n".join(formatted) + ";"
    lines += [
        "",
        f"-- inserted {len(rows)} rows",
    ]
    if len(rows) != EXPECTED_ROW_COUNT:
        raise RuntimeError(
            f"expected {EXPECTED_ROW_COUNT} demo rows, got {len(rows)}"
        )
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"output path (default: {DEFAULT_OUTPUT})",
    )
    args = parser.parse_args(argv)

    sql = generate_seed_sql()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(sql, encoding="utf-8")
    print(f"wrote {len(sql)} bytes to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
