#!/usr/bin/env python3
"""Initialize the complete local DataPaw environment on Windows, macOS, or Linux."""

from __future__ import annotations

import argparse
import json
import os
import sys
import tempfile
from pathlib import Path

from _local_common import (
    ensure_environment,
    repository_root,
    resolve_command,
    run,
    venv_executable,
)


def parser() -> argparse.ArgumentParser:
    result = argparse.ArgumentParser(description=__doc__)
    result.add_argument("--skip-build", action="store_true")
    result.add_argument("--skip-npm-install", action="store_true")
    result.add_argument("--context-python", default=None)
    result.add_argument("--uv", default=os.getenv("UV", "uv"))
    result.add_argument("--npm", default=os.getenv("NPM", "npm"))
    result.add_argument("--skip-context", action="store_true")
    result.add_argument("--skip-mcp-config", action="store_true")
    result.add_argument("--skip-cli-link", action="store_true")
    return result


def initialize_context(
    root: Path,
    *,
    uv: str,
    npm: str,
    python_spec: str | None,
    skip_build: bool,
    skip_npm_install: bool,
) -> None:
    context = root / "packages" / "datapaw-context"
    frontend = context / "frontend"
    requirements = context / "requirements.lock.txt"
    if python_spec is None:
        version_file = context / ".python-version"
        python_spec = (
            version_file.read_text(encoding="utf-8").strip()
            if version_file.exists()
            else "3.12"
        )

    context_venv = context / ".venv"
    run(
        [
            uv,
            "venv",
            "--no-project",
            "--allow-existing",
            "--python",
            python_spec,
            context_venv,
        ],
    )
    context_python = venv_executable(context_venv, "python")
    if not context_python.exists():
        raise RuntimeError(
            f"Expected Python environment was not created: {context_python}"
        )
    run([uv, "pip", "install", "--python", context_python, "-r", requirements])
    run(
        [
            uv,
            "pip",
            "install",
            "--python",
            context_python,
            "--editable",
            context,
            "--no-deps",
        ],
    )

    if not skip_npm_install:
        run(
            [npm, "ci" if (frontend / "package-lock.json").exists() else "install"],
            cwd=frontend,
        )
    if not skip_build:
        run([npm, "run", "build"], cwd=frontend)
        if not (frontend / "dist" / "index.html").exists():
            raise RuntimeError("Frontend build did not create dist/index.html")


def install_cli_launcher(root: Path, datapaw: Path) -> Path:
    configured = os.getenv("DATAPAW_CLI_BIN_DIR", "").strip()
    if configured:
        bin_dir = Path(configured).expanduser().resolve()
    elif os.name == "nt":
        bin_dir = (
            Path(os.getenv("LOCALAPPDATA", Path.home() / "AppData" / "Local"))
            / "DataPaw"
            / "bin"
        )
    else:
        bin_dir = Path.home() / ".local" / "bin"
    bin_dir.mkdir(parents=True, exist_ok=True)

    if os.name == "nt":
        launcher = bin_dir / "datapaw.cmd"
        marker = "REM Generated by DataPaw init_local.py"
        if launcher.exists() and marker not in launcher.read_text(
            encoding="utf-8", errors="ignore"
        ):
            raise RuntimeError(f"Refusing to replace existing command: {launcher}")
        launcher.write_text(
            f'{marker}\r\n@"{datapaw}" %*\r\n', encoding="utf-8", newline=""
        )
    else:
        launcher = bin_dir / "datapaw"
        if launcher.is_symlink():
            target = launcher.resolve(strict=False)
            if target != datapaw.resolve() and root not in target.parents:
                raise RuntimeError(
                    f"Refusing to replace existing link: {launcher} -> {target}"
                )
            launcher.unlink()
        elif launcher.exists():
            raise RuntimeError(f"Refusing to replace existing command: {launcher}")
        launcher.symlink_to(datapaw)
    return launcher


def main(argv: list[str] | None = None) -> int:
    args = parser().parse_args(argv)
    root = repository_root()
    ensure_environment(root)
    try:
        uv = resolve_command(args.uv)
        npm = resolve_command(args.npm) if not args.skip_context else args.npm
    except FileNotFoundError as exc:
        print(exc, file=sys.stderr)
        return 1

    if not args.skip_context:
        initialize_context(
            root,
            uv=uv,
            npm=npm,
            python_spec=args.context_python,
            skip_build=args.skip_build,
            skip_npm_install=args.skip_npm_install,
        )

    workspace_venv = root / ".venv"
    workspace_python = venv_executable(workspace_venv, "python")
    with tempfile.NamedTemporaryFile(
        prefix="datapaw-workspace-", suffix=".txt", delete=False
    ) as handle:
        requirements = Path(handle.name)
    try:
        run(
            [
                uv,
                "export",
                "--all-packages",
                "--frozen",
                "--format",
                "requirements-txt",
                "--no-emit-workspace",
                "--output-file",
                requirements,
            ],
            cwd=root,
            quiet=True,
        )
        run([uv, "venv", "--allow-existing", workspace_venv], cwd=root)
        run(
            [
                uv,
                "pip",
                "sync",
                "--python",
                workspace_python,
                "--require-hashes",
                requirements,
            ],
            cwd=root,
        )
        run(
            [
                uv,
                "pip",
                "install",
                "--python",
                workspace_python,
                "--no-deps",
                "--editable",
                root / "packages" / "datapaw-context",
                "--editable",
                root / "packages" / "datapaw-host-core",
                "--editable",
                root / "packages" / "datapaw-cli",
                "--editable",
                root / "packages" / "datapaw-skills",
            ],
            cwd=root,
        )
    finally:
        requirements.unlink(missing_ok=True)

    datapaw = venv_executable(workspace_venv, "datapaw")
    if not datapaw.exists():
        raise RuntimeError(f"Expected DataPaw CLI was not installed: {datapaw}")

    launcher: Path | None = None
    if not args.skip_cli_link:
        launcher = install_cli_launcher(root, datapaw)

    if not args.skip_mcp_config:
        base_url = os.getenv("DATAPAW_CM_BASE_URL", "http://127.0.0.1:8765").rstrip("/")
        config = [
            {
                "name": "databridge",
                "is_stateful": False,
                "mcp_config": {
                    "type": "http_mcp",
                    "url": f"{base_url}/mcp/v1/cm",
                    "headers": {},
                    "timeout": 2400.0,
                },
                "enable_tools": None,
                "disable_tools": None,
                "execution_timeout": 2400.0,
            }
        ]
        with tempfile.NamedTemporaryFile(
            "w", prefix="datapaw-mcp-", suffix=".json", encoding="utf-8", delete=False
        ) as handle:
            json.dump(config, handle)
            import_path = Path(handle.name)
        try:
            run([datapaw, "mcp", "import", import_path], cwd=root)
        finally:
            import_path.unlink(missing_ok=True)

    print("Local initialization complete.")
    if launcher:
        print(f"DataPaw CLI command: {launcher}")
        if str(launcher.parent) not in os.getenv("PATH", "").split(os.pathsep):
            print(f"Add {launcher.parent} to PATH, then open a new terminal.")
    print("Run: datapaw --help")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
